# Generated by Django 2.2.4 on 2020-10-17 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MobikeApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banco',
        ),
        migrations.DeleteModel(
            name='Bicicleta',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Comuna',
        ),
        migrations.DeleteModel(
            name='Contrato',
        ),
        migrations.DeleteModel(
            name='Estacionamiento',
        ),
        migrations.DeleteModel(
            name='Gps',
        ),
        migrations.DeleteModel(
            name='ReporteUso',
        ),
        migrations.DeleteModel(
            name='TarjetaCredito',
        ),
        migrations.DeleteModel(
            name='TarjetaMuni',
        ),
        migrations.DeleteModel(
            name='Zona',
        ),
    ]
