# Generated by Django 2.2.4 on 2020-10-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MobikeApp', '0002_auto_20201017_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'banco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id_bc', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bicicleta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1, unique=True)),
                ('nombres', models.TextField(unique=True)),
                ('apellidos', models.TextField(unique=True)),
                ('direccion', models.TextField(unique=True)),
                ('numero', models.FloatField(unique=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('direccion', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('num_contrato', models.IntegerField(primary_key=True, serialize=False)),
                ('direccion', models.TextField(unique=True)),
                ('fecha_creacion', models.TextField(unique=True)),
                ('fecha_termino', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'estacionamiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gps',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('latitud', models.TextField(unique=True)),
                ('longitud', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'gps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReporteUso',
            fields=[
                ('nro_reporte', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha', models.TextField(unique=True)),
                ('rut', models.FloatField(unique=True)),
                ('id', models.FloatField(unique=True)),
                ('id1', models.FloatField(unique=True)),
            ],
            options={
                'db_table': 'reporte_uso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TarjetaCredito',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('verificador', models.TextField(unique=True)),
                ('fecha_vencimiento', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'tarjeta_credito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TarjetaMuni',
            fields=[
                ('numero', models.BigIntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=1, unique=True)),
            ],
            options={
                'db_table': 'tarjeta_muni',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('direccion', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'zona',
                'managed': False,
            },
        ),
    ]
