# Generated by Django 3.0.7 on 2020-10-17 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MobikeApp', '0003_banco_bicicleta_cliente_comuna_contrato_estacionamiento_gps_reporteuso_tarjetacredito_tarjetamuni_zo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banco',
        ),
        migrations.DeleteModel(
            name='Bicicleta',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Comuna',
        ),
        migrations.DeleteModel(
            name='Contrato',
        ),
        migrations.DeleteModel(
            name='Estacionamiento',
        ),
        migrations.DeleteModel(
            name='Gps',
        ),
        migrations.DeleteModel(
            name='ReporteUso',
        ),
        migrations.DeleteModel(
            name='TarjetaCredito',
        ),
        migrations.DeleteModel(
            name='TarjetaMuni',
        ),
        migrations.DeleteModel(
            name='Zona',
        ),
    ]
