# Generated by Django 3.0.7 on 2020-10-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MobikeApp', '0004_auto_20201017_0535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
