# Generated by Django 3.0.7 on 2020-10-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobikeApp', '0005_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'BANCO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bicicleta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombres', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'CLIENTE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'COMUNA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('num_contrato', models.IntegerField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=45)),
                ('fecha_creacion', models.DateField()),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('email', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'CONTRATO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'ESTACIONAMIENTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gps',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('lalitud', models.CharField(max_length=45)),
                ('longitud', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'GPS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReporteUso',
            fields=[
                ('nro_reporte', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'REPORTE_USO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TarjetaCredito',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('verificado', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
            ],
            options={
                'db_table': 'TARJETA_CREDITO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TarjetaMuni',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'TARJETA_MUNI',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'ZONA',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
